#!/bin/bash  
#Script to print all the elements of the array  
  
#declaring the array  
declare -a example_array=( "Welcome""To""geetanjali" )  
  
#Printing all the elements  
echo "${example_array[@]}"
